---
- hosts: webserver
  become: true
  become_user: root
  tasks:
    - name: Installing httpd in host server
      yum: name=httpd state=present
    - name: restart httpd server
      service: name=httpd state=restarted
